# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import word2vec_pb2 as word2vec__pb2


class Word2VecServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EmbedWords = channel.unary_unary(
                '/Word2VecService/EmbedWords',
                request_serializer=word2vec__pb2.EmbedWordsRequest.SerializeToString,
                response_deserializer=word2vec__pb2.EmbedWordsResponse.FromString,
                )
        self.Similarity = channel.unary_unary(
                '/Word2VecService/Similarity',
                request_serializer=word2vec__pb2.SimilarityRequest.SerializeToString,
                response_deserializer=word2vec__pb2.SimilarityResponse.FromString,
                )


class Word2VecServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EmbedWords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Similarity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Word2VecServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EmbedWords': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedWords,
                    request_deserializer=word2vec__pb2.EmbedWordsRequest.FromString,
                    response_serializer=word2vec__pb2.EmbedWordsResponse.SerializeToString,
            ),
            'Similarity': grpc.unary_unary_rpc_method_handler(
                    servicer.Similarity,
                    request_deserializer=word2vec__pb2.SimilarityRequest.FromString,
                    response_serializer=word2vec__pb2.SimilarityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Word2VecService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Word2VecService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EmbedWords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Word2VecService/EmbedWords',
            word2vec__pb2.EmbedWordsRequest.SerializeToString,
            word2vec__pb2.EmbedWordsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Similarity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Word2VecService/Similarity',
            word2vec__pb2.SimilarityRequest.SerializeToString,
            word2vec__pb2.SimilarityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
