# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: word2vec.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eword2vec.proto\"\x1e\n\tEmbedding\x12\x11\n\tembedding\x18\x01 \x03(\x02\"\"\n\x11\x45mbedWordsRequest\x12\r\n\x05words\x18\x01 \x03(\t\"4\n\x12\x45mbedWordsResponse\x12\x1e\n\nembeddings\x18\x01 \x03(\x0b\x32\n.Embedding\"U\n\x11SimilarityRequest\x12\x1f\n\x0b\x65mbeddings1\x18\x01 \x03(\x0b\x32\n.Embedding\x12\x1f\n\x0b\x65mbeddings2\x18\x02 \x03(\x0b\x32\n.Embedding\"(\n\x12SimilarityResponse\x12\x12\n\nsimilarity\x18\x01 \x01(\x02\x32\x83\x01\n\x0fWord2VecService\x12\x37\n\nEmbedWords\x12\x12.EmbedWordsRequest\x1a\x13.EmbedWordsResponse\"\x00\x12\x37\n\nSimilarity\x12\x12.SimilarityRequest\x1a\x13.SimilarityResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'word2vec_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EMBEDDING']._serialized_start=18
  _globals['_EMBEDDING']._serialized_end=48
  _globals['_EMBEDWORDSREQUEST']._serialized_start=50
  _globals['_EMBEDWORDSREQUEST']._serialized_end=84
  _globals['_EMBEDWORDSRESPONSE']._serialized_start=86
  _globals['_EMBEDWORDSRESPONSE']._serialized_end=138
  _globals['_SIMILARITYREQUEST']._serialized_start=140
  _globals['_SIMILARITYREQUEST']._serialized_end=225
  _globals['_SIMILARITYRESPONSE']._serialized_start=227
  _globals['_SIMILARITYRESPONSE']._serialized_end=267
  _globals['_WORD2VECSERVICE']._serialized_start=270
  _globals['_WORD2VECSERVICE']._serialized_end=401
# @@protoc_insertion_point(module_scope)
